[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
goodbye_cruel_world = "66cXyUmo2dFRzGN7hXQU9VBqMMtPyLWnHQ1rMR1cve7p"
hello_again_world = "5bGFELeNyFmaxpdDHreMkpvUatakT7rMML3BmJCgDLVb"
hello_world = "DNPFtc5GRME1BNVV1caSgnxK28GvKduRG31BrpwAgA3u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
